version: '3.8'


services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend


  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    env_file:
      - ../.env

